Q.1  Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randint(0,100,size=(4, 4)), columns=list('ABCD'))

In [3]:
df

    A   B   C   D
0  46  67  58  70
1  12  60  51  98
2  79  88  81  69
3  44  45  18  75

In [4]:

df.rename(columns = {'A':'Random_value_1','B':'Random_value_2','C':'Random_value_3','D':'Random_value_4'}, inplace = True)

 Q.2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [5]:
df

   Random_value_1  Random_value_2  Random_value_3  Random_value_4
0              46              67              58              70
1              12              60              51              98
2              79              88              81              69
3              44              45              18              75

Q.3 Find the descriptive statistics of the 'df' dataframe.

In [7]:
df = pd.DataFrame(df)

In [8]:
df

   Random_value_1  Random_value_2  Random_value_3  Random_value_4
0              46              67              58              70
1              12              60              51              98
2              79              88              81              69
3              44              45              18              75

In [10]:
Dataframe = df['Random_value_1'].describe()

In [11]:
Dataframe

count     4.000000
mean     45.250000
std      27.366342
min      12.000000
25%      36.000000
50%      45.000000
75%      54.250000
max      79.000000
Name: Random_value_1, dtype: float64

In [12]:
df.describe(include='all')

       Random_value_1  Random_value_2  Random_value_3  Random_value_4
count        4.000000          4.0000        4.000000        4.000000
mean        45.250000         65.0000       52.000000       78.000000
std         27.366342         17.8699       26.038433       13.589211
min         12.000000         45.0000       18.000000       69.000000
25%         36.000000         56.2500       42.750000       69.750000
50%         45.000000         63.5000       54.500000       72.500000
75%         54.250000         72.2500       63.750000       80.750000
max         79.000000         88.0000       81.000000       98.000000

Q.4 Check for the null values in 'df' and find the data type of the columns.

In [13]:
df.isnull().values.any()

False

In [14]:
df.isnull().sum().sum()

0

In [15]:
df = df.dtypes

Q.5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [16]:
df

Random_value_1    int64
Random_value_2    int64
Random_value_3    int64
Random_value_4    int64
dtype: object

In [18]:
df.head()

Random_value_1    int64
Random_value_2    int64
Random_value_3    int64
Random_value_4    int64
dtype: object

In [21]:
df = df.loc['Random_value_1']

In [22]:
df

dtype('int64')